from PyQt5 import QtCore, QtGui, QtWidgets

QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)

class Ui_about_window(object):
    def setupUi(self, about_window):
        about_window.setObjectName("about_window")
        about_window.resize(600, 300)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        about_window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("tomato.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        about_window.setWindowIcon(icon)
        self.main_widget = QtWidgets.QWidget(about_window)
        self.main_widget.setObjectName("main_widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.main_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(39, 39, 521, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.main_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.about_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.about_label.setFont(font)
        self.about_label.setAlignment(QtCore.Qt.AlignCenter)
        self.about_label.setObjectName("about_label")
        self.main_layout.addWidget(self.about_label, 0, 0, 1, 1)
        self.logo_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("about_logo.png"))
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.main_layout.addWidget(self.logo_label, 1, 0, 1, 1)
        self.pomopal_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pomopal_label.setFont(font)
        self.pomopal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pomopal_label.setObjectName("pomopal_label")
        self.main_layout.addWidget(self.pomopal_label, 2, 0, 1, 1)
        self.version_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.version_label.setAlignment(QtCore.Qt.AlignCenter)
        self.version_label.setObjectName("version_label")
        self.main_layout.addWidget(self.version_label, 3, 0, 1, 1)
        self.creator_frame = QtWidgets.QFrame(self.main_widget)
        self.creator_frame.setGeometry(QtCore.QRect(40, 240, 521, 31))
        self.creator_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.creator_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.creator_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.creator_frame.setObjectName("creator_frame")
        self.creator_label = QtWidgets.QLabel(self.creator_frame)
        self.creator_label.setGeometry(QtCore.QRect(180, 0, 201, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.creator_label.setFont(font)
        self.creator_label.setAlignment(QtCore.Qt.AlignCenter)
        self.creator_label.setObjectName("creator_label")
        self.creator_image = QtWidgets.QLabel(self.creator_frame)
        self.creator_image.setGeometry(QtCore.QRect(140, 0, 41, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.creator_image.setFont(font)
        self.creator_image.setText("")
        self.creator_image.setPixmap(QtGui.QPixmap("atom_mono.png"))
        self.creator_image.setAlignment(QtCore.Qt.AlignCenter)
        self.creator_image.setObjectName("creator_image")
        self.back_btn = QtWidgets.QPushButton(self.main_widget)
        self.back_btn.setGeometry(QtCore.QRect(10, 12, 91, 31))
        self.back_btn.setObjectName("back_btn")
        about_window.setCentralWidget(self.main_widget)

        self.retranslateUi(about_window)
        QtCore.QMetaObject.connectSlotsByName(about_window)

    def retranslateUi(self, about_window):
        _translate = QtCore.QCoreApplication.translate
        about_window.setWindowTitle(_translate("about_window", "PomoPal v0.3"))
        self.about_label.setText(_translate("about_window", "About"))
        self.pomopal_label.setText(_translate("about_window", "PomoPal"))
        self.version_label.setText(_translate("about_window", "Version 0.3"))
        self.creator_label.setText(_translate("about_window", "Made By Ansh Thaker"))
        self.back_btn.setText(_translate("about_window", "< Back"))
