from PyQt5 import QtCore, QtGui, QtWidgets
from settings import Settings

QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)

settings = Settings()

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(600, 300)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        main_window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("tomato.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)
        self.main_widget = QtWidgets.QWidget(main_window)
        self.main_widget.setObjectName("main_widget")
        self.tabs = QtWidgets.QTabWidget(self.main_widget)
        self.tabs.setGeometry(QtCore.QRect(0, 50, 600, 161))
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabs.setObjectName("tabs")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.pomo_timer_label = QtWidgets.QLabel(self.tab1)
        self.pomo_timer_label.setGeometry(QtCore.QRect(0, 20, 591, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pomo_timer_label.setFont(font)
        self.pomo_timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pomo_timer_label.setObjectName("pomo_timer_label")
        self.tabs.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.short_break_label = QtWidgets.QLabel(self.tab2)
        self.short_break_label.setGeometry(QtCore.QRect(0, 20, 591, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.short_break_label.setFont(font)
        self.short_break_label.setAlignment(QtCore.Qt.AlignCenter)
        self.short_break_label.setObjectName("short_break_label")
        self.tabs.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.long_break_label = QtWidgets.QLabel(self.tab3)
        self.long_break_label.setGeometry(QtCore.QRect(0, 20, 591, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.long_break_label.setFont(font)
        self.long_break_label.setAlignment(QtCore.Qt.AlignCenter)
        self.long_break_label.setObjectName("long_break_label")
        self.tabs.addTab(self.tab3, "")
        self.gridLayoutWidget = QtWidgets.QWidget(self.main_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 210, 601, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.controls_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.controls_grid_layout.setContentsMargins(5, 5, 5, 5)
        self.controls_grid_layout.setObjectName("controls_grid_layout")
        self.start_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_btn.setObjectName("start_btn")
        self.controls_grid_layout.addWidget(self.start_btn, 0, 0, 1, 1)
        self.pause_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pause_btn.setObjectName("pause_btn")
        self.controls_grid_layout.addWidget(self.pause_btn, 0, 1, 1, 1)
        self.reset_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.reset_btn.setObjectName("reset_btn")
        self.controls_grid_layout.addWidget(self.reset_btn, 0, 3, 1, 1)
        self.skip_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.skip_btn.setObjectName("skip_btn")
        self.controls_grid_layout.addWidget(self.skip_btn, 0, 2, 1, 1)
        self.pomo_counter_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pomo_counter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pomo_counter_label.setObjectName("pomo_counter_label")
        self.controls_grid_layout.addWidget(self.pomo_counter_label, 1, 0, 1, 4)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.main_widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(370, 0, 231, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.page_btns_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.page_btns_grid_layout.setContentsMargins(5, 5, 5, 5)
        self.page_btns_grid_layout.setObjectName("page_btns_grid_layout")
        self.settings_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.settings_btn.setFont(font)
        self.settings_btn.setObjectName("settings_btn")
        self.page_btns_grid_layout.addWidget(self.settings_btn, 0, 1, 1, 1)
        self.about_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.about_btn.setObjectName("about_btn")
        self.page_btns_grid_layout.addWidget(self.about_btn, 0, 0, 1, 1)
        main_window.setCentralWidget(self.main_widget)

        self.retranslateUi(main_window)
        self.tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "PomoPal v0.3"))
        full_secs_pomo = 60 * int(settings.pomodoro_time)
        mins_pomo, secs_pomo = divmod(full_secs_pomo, 60)
        self.pomo_timer_label.setText(f'{mins_pomo:02d}:{secs_pomo:02d}')

        self.tabs.setTabText(self.tabs.indexOf(self.tab1), _translate("main_window", "Pomodoro"))
        full_secs_short = 60 * int(settings.short_break_time)
        mins_short, secs_short = divmod(full_secs_short, 60)
        self.short_break_label.setText(f'{mins_short:02d}:{secs_short:02d}')
        self.tabs.setTabText(self.tabs.indexOf(self.tab2), _translate("main_window", "Short Break"))
        full_secs_long = 60 * int(settings.long_break_time)
        mins_long, secs_long = divmod(full_secs_long, 60)
        self.long_break_label.setText(f'{mins_long:02d}:{secs_long:02d}')
        self.tabs.setTabText(self.tabs.indexOf(self.tab3), _translate("main_window", "Long Break"))
        self.start_btn.setText(_translate("main_window", "Start"))
        self.pause_btn.setText(_translate("main_window", "Pause"))
        self.reset_btn.setText(_translate("main_window", "Reset"))
        self.skip_btn.setText(_translate("main_window", "Skip"))
        self.pomo_counter_label.setText(_translate("main_window", "Pomodoros: 0"))
        self.settings_btn.setText(_translate("main_window", "Settings"))
        self.about_btn.setText(_translate("main_window", "About"))
