from PyQt5 import QtCore, QtGui, QtWidgets
from settings import Settings

QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)

settings = Settings()

class Ui_settings_window(object):
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.resize(600, 300)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        settings_window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("tomato.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        settings_window.setWindowIcon(icon)
        self.main_widget = QtWidgets.QWidget(settings_window)
        self.main_widget.setObjectName("main_widget")
        self.main_scroll_area = QtWidgets.QScrollArea(self.main_widget)
        self.main_scroll_area.setGeometry(QtCore.QRect(-1, 49, 600, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_scroll_area.sizePolicy().hasHeightForWidth())
        self.main_scroll_area.setSizePolicy(sizePolicy)
        self.main_scroll_area.setMinimumSize(QtCore.QSize(0, 0))
        self.main_scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_scroll_area.setFrameShadow(QtWidgets.QFrame.Plain)
        self.main_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.main_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.main_scroll_area.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.main_scroll_area.setWidgetResizable(True)
        self.main_scroll_area.setObjectName("main_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 600, 350))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(600, 350))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 581, 334))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.main_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.main_grid_layout.setContentsMargins(10, 10, 10, 10)
        self.main_grid_layout.setObjectName("main_grid_layout")
        self.long_break_interval = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.long_break_interval.setFont(font)
        self.long_break_interval.setObjectName("long_break_interval")
        self.main_grid_layout.addWidget(self.long_break_interval, 6, 0, 1, 1)
        self.long_break_interval_spin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.long_break_interval_spin.setFont(font)
        self.long_break_interval_spin.setMinimum(1)
        self.long_break_interval_spin.setMaximum(2147483647)
        self.long_break_interval_spin.setProperty("value", 4)
        self.long_break_interval_spin.setObjectName("long_break_interval_spin")
        self.long_break_interval_spin.setValue(settings.long_break_interval)
        self.long_break_interval_spin.valueChanged.connect(self.set_long_break_interval)
        self.main_grid_layout.addWidget(self.long_break_interval_spin, 6, 1, 1, 1)
        self.long_break_time_spin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.long_break_time_spin.setFont(font)
        self.long_break_time_spin.setMaximum(2147483647)
        self.long_break_time_spin.setProperty("value", 15)
        self.long_break_time_spin.setObjectName("long_break_time_spin")
        self.long_break_time_spin.setValue(settings.long_break_time)
        self.long_break_time_spin.valueChanged.connect(self.set_long_break_time)
        self.main_grid_layout.addWidget(self.long_break_time_spin, 4, 1, 1, 1)
        self.short_break_time = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.short_break_time.setFont(font)
        self.short_break_time.setObjectName("short_break_time")
        self.main_grid_layout.addWidget(self.short_break_time, 3, 0, 1, 1)
        self.pomodoro_time = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pomodoro_time.setFont(font)
        self.pomodoro_time.setObjectName("pomodoro_time")
        self.main_grid_layout.addWidget(self.pomodoro_time, 2, 0, 1, 1)
        self.pomodoro_time_spin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pomodoro_time_spin.setFont(font)
        self.pomodoro_time_spin.setMaximum(2147483647)
        self.pomodoro_time_spin.setProperty("value", 25)
        self.pomodoro_time_spin.setObjectName("pomodoro_time_spin")
        self.pomodoro_time_spin.setValue(settings.pomodoro_time)
        self.pomodoro_time_spin.valueChanged.connect(self.set_pomodoro_time)
        self.main_grid_layout.addWidget(self.pomodoro_time_spin, 2, 1, 1, 1)
        self.time_section = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.time_section.setFont(font)
        self.time_section.setObjectName("time_section")
        self.main_grid_layout.addWidget(self.time_section, 1, 0, 1, 1)
        self.alarm_section = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.alarm_section.setFont(font)
        self.alarm_section.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.alarm_section.setObjectName("alarm_section")
        self.main_grid_layout.addWidget(self.alarm_section, 7, 0, 1, 1)
        self.long_break_time = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.long_break_time.setFont(font)
        self.long_break_time.setObjectName("long_break_time")
        self.main_grid_layout.addWidget(self.long_break_time, 4, 0, 1, 1)
        self.short_break_time_spin = QtWidgets.QSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.short_break_time_spin.setFont(font)
        self.short_break_time_spin.setMaximum(2147483647)
        self.short_break_time_spin.setProperty("value", 5)
        self.short_break_time_spin.setObjectName("short_break_time_spin")
        self.short_break_time_spin.setValue(settings.short_break_time)
        self.short_break_time_spin.valueChanged.connect(self.set_short_break_time)
        self.main_grid_layout.addWidget(self.short_break_time_spin, 3, 1, 1, 1)
        self.auto_start_timers = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.auto_start_timers.setFont(font)
        self.auto_start_timers.setObjectName("auto_start_timers")
        self.main_grid_layout.addWidget(self.auto_start_timers, 5, 0, 1, 1)
        self.auto_start_timers_check = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.auto_start_timers_check.setFont(font)
        self.auto_start_timers_check.setText("")
        self.auto_start_timers_check.setObjectName("auto_start_timers_check")
        self.auto_start_timers_check.setChecked(settings.auto_start_timer)
        self.auto_start_timers_check.stateChanged.connect(self.set_auto_start_timer)
        self.main_grid_layout.addWidget(self.auto_start_timers_check, 5, 1, 1, 1)
        self.timer_section = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timer_section.setFont(font)
        self.timer_section.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.timer_section.setObjectName("timer_section")
        self.main_grid_layout.addWidget(self.timer_section, 0, 0, 1, 1)
        self.alarm = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alarm.setFont(font)
        self.alarm.setObjectName("alarm")
        self.main_grid_layout.addWidget(self.alarm, 11, 0, 1, 1)
        self.alarm_check = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alarm_check.setFont(font)
        self.alarm_check.setText("")
        self.alarm_check.setObjectName("alarm_check")
        self.alarm_check.setChecked(settings.alarm)
        self.alarm_check.stateChanged.connect(self.set_alarm)
        self.main_grid_layout.addWidget(self.alarm_check, 11, 1, 1, 1)
        self.main_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.settings_label = QtWidgets.QLabel(self.main_widget)
        self.settings_label.setGeometry(QtCore.QRect(0, 0, 601, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.settings_label.setFont(font)
        self.settings_label.setAlignment(QtCore.Qt.AlignCenter)
        self.settings_label.setObjectName("settings_label")
        self.back_btn = QtWidgets.QPushButton(self.main_widget)
        self.back_btn.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.back_btn.setObjectName("back_btn")
        settings_window.setCentralWidget(self.main_widget)

        self.retranslateUi(settings_window)
        QtCore.QMetaObject.connectSlotsByName(settings_window)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "PomoPal v0.3"))
        self.long_break_interval.setText(_translate("settings_window", "Long Break Interval"))
        self.short_break_time.setText(_translate("settings_window", "Short Break"))
        self.pomodoro_time.setText(_translate("settings_window", "Pomodoro"))
        self.time_section.setText(_translate("settings_window", "Time in mins (reset the timer to see changes)"))
        self.alarm_section.setText(_translate("settings_window", "Alarm"))
        self.long_break_time.setText(_translate("settings_window", "Long Break"))
        self.auto_start_timers.setText(_translate("settings_window", "Auto Start Timers"))
        self.timer_section.setText(_translate("settings_window", "Timer"))
        self.alarm.setText(_translate("settings_window", "Alarm"))
        self.settings_label.setText(_translate("settings_window", "Settings"))
        self.back_btn.setText(_translate("settings_window", "< Back"))

    def set_pomodoro_time(self):
        settings.settings.setValue('pomodoro_time', str(self.pomodoro_time_spin.value()))

    def set_short_break_time(self):
        settings.settings.setValue('short_break_time', str(self.short_break_time_spin.value()))

    def set_long_break_time(self):
        settings.settings.setValue('long_break_time', str(self.long_break_time_spin.value()))

    def set_auto_start_timer(self):
        settings.settings.setValue('auto_start_timer', self.auto_start_timers_check.isChecked())

    def set_long_break_interval(self):
        settings.settings.setValue('long_break_interval', str(self.long_break_interval_spin.value()))

    def set_alarm(self):
        settings.settings.setValue('alarm', self.alarm_check.isChecked())
